CREATE TABLE etnetStock (
    Datetime        date,
    Symbol        varchar(8),
    Nominal_price        money,
    High        money,
    varchar_Share_Tr        varchar(20),
    Share_Tr        double precision,
    Prev_Close        money,
    One_Month_High        money,
    Varchar_MKT_Cap        varchar(20),
    MKT_Cap        double precision,
    Low        money,
    Varchar_Turnover        varchar(20),
    Turnover        double precision,
    Open        money,
    One_Month_Low        money,
    Varchar_Short_Sell        varchar(20),
    Short_Sell        double precision,
    Bid        money,
    Ten_D_SMA        money,
    Ask        money,
    Twenty_D_SMA        money,
    No_of_Tr        integer,
    Fifty_D_SMA        money,
    Amount_T        money,
    Hundered_D_SMA        money,
    VWAP        money,
    T250_D_SMA        money,
    Fifty_two_W_High        money,
    Fifty_two_W_Low        money,
    Admission_Fee        money,
    Fourteen_D_RSI        money,
    Varchar_Spread        varchar(20),
    Spread        money,
    Ten_D_R_of_Return        double precision,
    PE_RatioAndEst        varchar(20),
    PE_Ratio        double precision,
    Est_PE_Ratio        double precision,
    Rate_of_Risk        varchar(20),
    YldAndEst        varchar(20),
    Yld        double precision,
    Est_Yld        double precision,
    Risk_Return_Rate        double precision,
    EPS        varchar(20),
    Beta        double precision,
    DPS        varchar(20),
    NBV_Per_Share        varchar(20)
);

CREATE TABLE googleStock (
    Datetime        date,
    Symbol        varchar(8),
    Nominal_price        money,
    Open        money,
    High        money,
    Low        money,
    varchar_Mkt_cap        varchar(20),
    Mkt_cap        double precision,
    PE_ratio        double precision,
    Div_yield        double precision,
    Prev_close        money,
    Fifty_two_wk_high        money,
    Fifty_two_wk_low        money
);

CREATE TABLE hkexStock (
    Datetime        date,
    Symbol        varchar(8),
    Nominal_Price        money,
    Prev_close        money,
    Open        money,
    Varchar_Turnover        varchar(20),
    Turnover        double precision,
    Varchar__Volume        varchar(20),
    Volume        double precision,
    Varchar_Mkt_cap        varchar(20),
    Mkt_cap        double precision,
    Bid        money,
    Ask        money,
    EPS_RMB        double precision,
    PE_ratio        double precision,
    Div_yield        double precision,
    High        money,
    Low        money,
    Fifty_two_wk_high        money,
    Fifty_two_wk_low        money
);

CREATE TABLE yahooStock(
    Datetime        date,
    Symbol        varchar(8),
    Nominal_price        money,
    Previous_Close        money,
    Open        money,
    Varchar_Bid        varchar(20),
    Varchar_Ask        varchar(20),
    Bid        double precision,
    BidNum        int,
    Ask        double precision,
    AskNum        int,
    Varchar_Days_Range        varchar(20),
    Varchar_52_Week_Range        varchar(20),
    Days_up        double precision,
    Days_down        double precision,
    Week_up        double precision,
    Week_down        double precision,
    Volume        double precision,
    Avg_Volume        double precision,
    Varchar_Market_Cap        varchar(20),
    Market_Cap        double precision,
    Beta        double precision,
    PE_Ratio_TTM        double precision,
    EPS_TTM        double precision,
    Earnings_Date        date,
    Varchar_Forward_Dividend_Yield        varchar(20),
    Ex_Dividend_Date        date,
    Oney_Target_Est        double precision
);

CREATE TABLE bloombergStock(
    Datetime        date,
    Symbol        varchar(8),
    Nominal_price        money,
    Open        money,
    Prev_Close        money,
    Volume        double precision,
    Market_Cap        double precision,
    Varchar_Market_Cap        varchar(20),
    Varchar_Day_Range        varchar(20),
    Day_High        money,
    Day_Low        money,
    Varchar_52Week_Range        varchar(20),
    Fifty_two_W_High        money,
    Fifty_two_W_Low        money,
    PE_Ratio        double precision,
    Bloomberg_Best_PE_Ratio        double precision,
    Bloomberg_Best_PEG_Ratio        double precision,
    Varchar_Shares_Outstanding        varchar(20),
    Shares_Outstanding        double precision,
    Price_to_Book_Ratio        double precision,
    Price_to_Sales_Ratio        double precision,
    One_Year_Return        double precision,
    Thirty_Day_Avg_Volume        double precision,
    EPS        double precision,
    Bloomberg_Best_EPS_Curr_Yr        double precision,
    Dividend        double precision,
    Last_Dividend_Reported        double precision
);
