INSERT INTO config  VALUES ('5', 'HSBC_Holdings', 'HSBC Holdings');
INSERT INTO config  VALUES ('11', 'Hang_Seng_Bank', 'Hang Seng Bank');
INSERT INTO config  VALUES ('23', 'Bank_of_E_Asia', 'Bank of E Asia');
INSERT INTO config  VALUES ('388', 'HKEx', 'HKEx');
INSERT INTO config  VALUES ('939', 'CCB', 'CCB');
INSERT INTO config  VALUES ('1299', 'AIA', 'AIA');
INSERT INTO config  VALUES ('1398', 'ICBC', 'ICBC');
INSERT INTO config  VALUES ('2318', 'Ping_An', 'Ping An');
INSERT INTO config  VALUES ('2388', 'BOC_Hong_Kong', 'BOC Hong Kong');
INSERT INTO config  VALUES ('2628', 'China_Life', 'China Life');
INSERT INTO config  VALUES ('3328', 'Bankcomm', 'Bankcomm');
INSERT INTO config  VALUES ('3988', 'Bank_of_China', 'Bank of China');
INSERT INTO config  VALUES ('2', 'CLP_Holdings', 'CLP Holdings');
INSERT INTO config  VALUES ('3', 'HK_China_Gas', 'HK & China Gas');
INSERT INTO config  VALUES ('6', 'Power_Assets', 'Power Assets');
INSERT INTO config  VALUES ('836', 'China_Res_Power', 'China Res Power');
INSERT INTO config  VALUES ('1038', 'CKI_Holdings', 'CKI Holdings');
INSERT INTO config  VALUES ('12', 'Henderson_Land', 'Henderson Land');
INSERT INTO config  VALUES ('16', 'SHK_Ppt', 'SHK Ppt');
INSERT INTO config  VALUES ('17', 'New_World_Dev', 'New World Dev');
INSERT INTO config  VALUES ('83', 'Sino_Land', 'Sino Land');
INSERT INTO config  VALUES ('101', 'Hang_Lung_Ppt', 'Hang Lung Ppt');
INSERT INTO config  VALUES ('688', 'China_Overseas', 'China Overseas');
INSERT INTO config  VALUES ('823', 'Link_REIT', 'Link REIT');
INSERT INTO config  VALUES ('1109', 'China_Res_Land', 'China Res Land');
INSERT INTO config  VALUES ('1113', 'CK_Asset', 'CK Asset');
INSERT INTO config  VALUES ('1997', 'Wharf_REIC', 'Wharf REIC');
INSERT INTO config  VALUES ('2007', 'Country_Garden', 'Country Garden');
INSERT INTO config  VALUES ('1', 'CKH_Holdings', 'CKH Holdings');
INSERT INTO config  VALUES ('19', 'Swire_Pacific_A', 'Swire Pacific A');
INSERT INTO config  VALUES ('27', 'Galaxy_Ent', 'Galaxy Ent');
INSERT INTO config  VALUES ('66', 'MTR_Corporation', 'MTR Corporation');
INSERT INTO config  VALUES ('144', 'China_Mer_Port', 'China Mer Port');
INSERT INTO config  VALUES ('151', 'Want_Want_China', 'Want Want China');
INSERT INTO config  VALUES ('175', 'Geely_Auto', 'Geely Auto');
INSERT INTO config  VALUES ('267', 'CITIC', 'CITIC');
INSERT INTO config  VALUES ('288', 'WH_Group', 'WH Group');
INSERT INTO config  VALUES ('386', 'Sinopec_Corp', 'Sinopec Corp');
INSERT INTO config  VALUES ('700', 'Tencent', 'Tencent');
INSERT INTO config  VALUES ('762', 'China_Unicom', 'China Unicom');
INSERT INTO config  VALUES ('857', 'PetroChina', 'PetroChina');
INSERT INTO config  VALUES ('883', 'CNOOC', 'CNOOC');
INSERT INTO config  VALUES ('941', 'China_Mobile', 'China Mobile');
INSERT INTO config  VALUES ('992', 'Lenovo_Group', 'Lenovo Group');
INSERT INTO config  VALUES ('1044', 'Hengan_Intl', 'Hengan Intl');
INSERT INTO config  VALUES ('1088', 'China_Shenhua', 'China Shenhua');
INSERT INTO config  VALUES ('1928', 'Sands_China_Ltd', 'Sands China Ltd');
INSERT INTO config  VALUES ('2018', 'AAC_Tech', 'AAC Tech');
INSERT INTO config  VALUES ('2319', 'Mengniu_Dairy', 'Mengniu Dairy');
INSERT INTO config  VALUES ('2382', 'Sunny_Optical', 'Sunny Optical');